name: Exclusive Labels

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

permissions:
  issues: write

jobs:
  enforce-exclusive-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove conflicting labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            검토 요청
            완료된 사항
            작업 요청
        if: >
          github.event.label.name == '검토 요청' ||
          github.event.label.name == '완료된 사항' ||
          github.event.label.name == '작업 요청'
